<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFramework>net10.0</TargetFramework>
	<Nullable>enable</Nullable>
	<ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Dtos\Calificaciones\" />
    <Folder Include="Dtos\Reproducciones\" />
    <Folder Include="Dtos\WatchLists\" />
    <Folder Include="Dtos\Personas\" />
    <Folder Include="Dtos\Peliculas\" />
    <Folder Include="Services\Calificacion\" />
    <Folder Include="Services\Reproduccion\" />
    <Folder Include="Services\WatchList\" />
    <Folder Include="Services\Persona\" />
    <Folder Include="Services\Pelicula\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\G3_Proyecto_CineStreamCR.DAL\G3_Proyecto_CineStreamCR.DAL.csproj" />
  </ItemGroup>

</Project>
