<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\G3_Proyecto_CineStreamCR.BLL\G3_Proyecto_CineStreamCR.BLL.csproj" />
    <ProjectReference Include="..\G3_Proyecto_CineStreamCR.DAL\G3_Proyecto_CineStreamCR.DAL.csproj" />
  </ItemGroup>

</Project>
