// <auto-generated />
using System;
using G3_Proyecto_CineStreamCR.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace G3_Proyecto_CineStreamCR.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260809220251_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("G3_Proyecto_CineStreamCR.DAL.Entidades.Calificacion", b =>
                {
                    b.Property<int>("IdCalificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdPelicula")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Puntuacion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Resena")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("IdCalificacion");

                    b.HasIndex("IdPelicula");

                    b.HasIndex("IdUsuario", "IdPelicula")
                        .IsUnique();

                    b.ToTable("Calificaciones");
                });

            modelBuilder.Entity("G3_Proyecto_CineStreamCR.DAL.Entidades.Genero", b =>
                {
                    b.Property<int>("IdGenero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("IdGenero");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Generos");
                });

            modelBuilder.Entity("G3_Proyecto_CineStreamCR.DAL.Entidades.Pelicula", b =>
                {
                    b.Property<int>("IdPelicula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Anio")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdDirector")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PosterUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<double>("Rating")
                        .HasColumnType("REAL");

                    b.Property<string>("Sinopsis")
                        .HasMaxLength(3000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("IdPelicula");

                    b.HasIndex("IdDirector");

                    b.ToTable("Peliculas");
                });

            modelBuilder.Entity("G3_Proyecto_CineStreamCR.DAL.Entidades.PeliculaActor", b =>
                {
                    b.Property<int>("IdPelicula")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdActor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Personaje")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("IdPelicula", "IdActor");

                    b.HasIndex("IdActor");

                    b.ToTable("PeliculaActores");
                });

            modelBuilder.Entity("G3_Proyecto_CineStreamCR.DAL.Entidades.PeliculaGenero", b =>
                {
                    b.Property<int>("IdPelicula")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdGenero")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdPelicula", "IdGenero");

                    b.HasIndex("IdGenero");

                    b.ToTable("PeliculaGeneros");
                });

            modelBuilder.Entity("G3_Proyecto_CineStreamCR.DAL.Entidades.Persona", b =>
                {
                    b.Property<int>("IdPersona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Biografia")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nacionalidad")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("IdPersona");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("G3_Proyecto_CineStreamCR.DAL.Entidades.Reproduccion", b =>
                {
                    b.Property<int>("IdReproduccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FechaUltimaReproduccion")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdPelicula")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SegundoActual")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdReproduccion");

                    b.HasIndex("IdPelicula");

                    b.HasIndex("IdUsuario", "IdPelicula")
                        .IsUnique();

                    b.ToTable("Reproducciones");
                });

            modelBuilder.Entity("G3_Proyecto_CineStreamCR.DAL.Entidades.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("G3_Proyecto_CineStreamCR.DAL.Entidades.WatchList", b =>
                {
                    b.Property<int>("IdWatchList")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("IdWatchList");

                    b.HasIndex("IdUsuario", "Nombre")
                        .IsUnique();

                    b.ToTable("WatchLists");
                });

            modelBuilder.Entity("G3_Proyecto_CineStreamCR.DAL.Entidades.WatchListPelicula", b =>
                {
                    b.Property<int>("IdWatchList")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdPelicula")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdWatchList", "IdPelicula");

                    b.HasIndex("IdPelicula");

                    b.ToTable("WatchListPeliculas");
                });

            modelBuilder.Entity("G3_Proyecto_CineStreamCR.DAL.Entidades.Calificacion", b =>
                {
                    b.HasOne("G3_Proyecto_CineStreamCR.DAL.Entidades.Pelicula", "Pelicula")
                        .WithMany("Calificaciones")
                        .HasForeignKey("IdPelicula")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("G3_Proyecto_CineStreamCR.DAL.Entidades.Usuario", "Usuario")
                        .WithMany("Calificaciones")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pelicula");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("G3_Proyecto_CineStreamCR.DAL.Entidades.Pelicula", b =>
                {
                    b.HasOne("G3_Proyecto_CineStreamCR.DAL.Entidades.Persona", "Director")
                        .WithMany("PeliculasDirigidas")
                        .HasForeignKey("IdDirector")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Director");
                });

            modelBuilder.Entity("G3_Proyecto_CineStreamCR.DAL.Entidades.PeliculaActor", b =>
                {
                    b.HasOne("G3_Proyecto_CineStreamCR.DAL.Entidades.Persona", "Actor")
                        .WithMany("PeliculasComoActor")
                        .HasForeignKey("IdActor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("G3_Proyecto_CineStreamCR.DAL.Entidades.Pelicula", "Pelicula")
                        .WithMany("PeliculaActores")
                        .HasForeignKey("IdPelicula")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Pelicula");
                });

            modelBuilder.Entity("G3_Proyecto_CineStreamCR.DAL.Entidades.PeliculaGenero", b =>
                {
                    b.HasOne("G3_Proyecto_CineStreamCR.DAL.Entidades.Genero", "Genero")
                        .WithMany("PeliculaGeneros")
                        .HasForeignKey("IdGenero")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("G3_Proyecto_CineStreamCR.DAL.Entidades.Pelicula", "Pelicula")
                        .WithMany("PeliculaGeneros")
                        .HasForeignKey("IdPelicula")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genero");

                    b.Navigation("Pelicula");
                });

            modelBuilder.Entity("G3_Proyecto_CineStreamCR.DAL.Entidades.Reproduccion", b =>
                {
                    b.HasOne("G3_Proyecto_CineStreamCR.DAL.Entidades.Pelicula", "Pelicula")
                        .WithMany("Reproducciones")
                        .HasForeignKey("IdPelicula")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("G3_Proyecto_CineStreamCR.DAL.Entidades.Usuario", "Usuario")
                        .WithMany("Reproducciones")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pelicula");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("G3_Proyecto_CineStreamCR.DAL.Entidades.WatchList", b =>
                {
                    b.HasOne("G3_Proyecto_CineStreamCR.DAL.Entidades.Usuario", "Usuario")
                        .WithMany("WatchLists")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("G3_Proyecto_CineStreamCR.DAL.Entidades.WatchListPelicula", b =>
                {
                    b.HasOne("G3_Proyecto_CineStreamCR.DAL.Entidades.Pelicula", "Pelicula")
                        .WithMany("WatchListPeliculas")
                        .HasForeignKey("IdPelicula")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("G3_Proyecto_CineStreamCR.DAL.Entidades.WatchList", "WatchList")
                        .WithMany("WatchListPeliculas")
                        .HasForeignKey("IdWatchList")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pelicula");

                    b.Navigation("WatchList");
                });

            modelBuilder.Entity("G3_Proyecto_CineStreamCR.DAL.Entidades.Genero", b =>
                {
                    b.Navigation("PeliculaGeneros");
                });

            modelBuilder.Entity("G3_Proyecto_CineStreamCR.DAL.Entidades.Pelicula", b =>
                {
                    b.Navigation("Calificaciones");

                    b.Navigation("PeliculaActores");

                    b.Navigation("PeliculaGeneros");

                    b.Navigation("Reproducciones");

                    b.Navigation("WatchListPeliculas");
                });

            modelBuilder.Entity("G3_Proyecto_CineStreamCR.DAL.Entidades.Persona", b =>
                {
                    b.Navigation("PeliculasComoActor");

                    b.Navigation("PeliculasDirigidas");
                });

            modelBuilder.Entity("G3_Proyecto_CineStreamCR.DAL.Entidades.Usuario", b =>
                {
                    b.Navigation("Calificaciones");

                    b.Navigation("Reproducciones");

                    b.Navigation("WatchLists");
                });

            modelBuilder.Entity("G3_Proyecto_CineStreamCR.DAL.Entidades.WatchList", b =>
                {
                    b.Navigation("WatchListPeliculas");
                });
#pragma warning restore 612, 618
        }
    }
}
